name: Build and Deploy Hugo

on:
  push:
    branches:
      - main
  repository_dispatch:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout site
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Checkout content
        uses: actions/checkout@v3
        with:
          repository: EnricoBDev/blog_content
          token: ${{ secrets.CONTENT_REPO_PAT }}
          path: content
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --ignoreCache

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
